development:
  database: t_wikiful_development
  adapter: postgresql
  host: localhost
  port: 5432

test:
  database: t_wikiful_test
  adapter: postgresql
  host: localhost
  port: 5432

staging:
  database: t_wikiful
  adapter: postgresql
  host: localhost
  port: 5432

production:
  database: t_wikiful
  adapter: postgresql
  host: localhost
  port: 5432